### ISSUE TITLE
Possible name mismatch for Manager objects

### ISSUE THREAD

**Issue by David-dp-** [lorenalexm/unity-browser-saving#1]
I have only looked through this code, not run it, but one thing that looks possibly off to me is that the manager object is named SceneManager in

https://github.com/lorenalexm/unity-browser-saving/blob/master/unity/Assets/Scripts/SceneManager.cs

but it's referenced as "Manager" in SendMessage("Manager", "OnReceiveData", data.target.result) in

https://github.com/lorenalexm/unity-browser-saving/blob/master/webgl/js/methods.js

I haven't noticed any place where a class instance can be named something other than the class name, but perhaps you do that somewhere.

**Comment by omgitsalexl** [comment]
First off let me apologize as this reply is being sent via my phone.

https://github.com/lorenalexm/unity-browser-saving/blob/master/webgl/js/methods.js

The call your seeing to the "Manager" in the above file, is actually referencing the name of a GameObject within the scene itself. This is how Unity designed the WebGL JavaScript interface between the player and the webpage, beyond my control there.

I won't deny though, that I could have named the GameObject within the scene something less ambiguous or better yet provided some documentation; this was just an evening experiment and never was fleshed out into anything comprehensive. 

I'm more than happy to assist anywhere I can, just make me aware. Until that then, I am going to close this issue; feel free to reopen if I missed something.

**Comment by omgitsalexl** [comment]
@David-dp- just for a bit further clarification, I've attached the following screenshot from the example scene in this repository. So the JavaScript file from the browser is sending a message to the _Manager_ game object and which has the _OnReceiveData_ method defined in the _SceneManager_ class.

The Unity Documentation tries to cover this concept a bit more; I've attached the link below.
https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html

![screen shot 2016-06-27 at 7 48 58 am](https://cloud.githubusercontent.com/assets/6470175/16383870/b311f482-3c3b-11e6-8e6e-3088f20a6e05.png)

**Comment by David-dp-** [comment]
Thanks, Alex. I have been looking at that Unity documentation and related
pages for a couple days. Another mystery is what JS namespace/object is
SendMessage defined for? Your code, and the doc page you link, show no obj
reference; yet, going into Chrome Dev Tools for a Unity WebGL build and
pasting a call to SendMessage there results in an error about SendMessage
not being defined -- just as I would expect. So how does your code avoid
that?

**Comment by David-dp-** [comment]
I mean that I wait for the WebGL build to load completely, then paste into
CDT console.

**Comment by omgitsalexl** [comment]
I've attached a paragraph directly from the Unity documentation, although it states its for the Web Player the concepts holds true for WebGL and the WebGL documentation even links to the Web Player section of the docs saying they are the same.

https://docs.unity3d.com/Manual/UnityWebPlayerandbrowsercommunication.html

> The Unity Web Player object has a function, SendMessage(), that can be called from a web page in order to call functions within Unity web player content. This function is very similar to the GameObject.SendMessage function in the Unity scripting API. When called from a web page you pass an object name, a function name and a single argument, and SendMessage() will call the given function in the given game object.

I would have to hazard a guess and say that _SendMessage_ is defined in the _/webgl/Release/webgl.js_ file though this file is ~34MB of text/script and I have never delved through its contents. If you look within the _index.html_, particularly the script block starting at line 105 you'll see that the _webgl.js_ is being loaded via an _XMLHttpRequest_ object ran via _asm.js_, this seems to solidify the fact that _SendMessage_ is defined within. Now I don't a deep understanding of how this couples together and plays out during run time, but it may explain as to why you're unable to make direct _SendMessage_ calls from the browser console.

**Comment by David-dp-** [comment]
Thanks for passing this info on, Alex.

When I couldn't get further with SendMessage, I looked around for other
approaches and found this one which is an order of magnitude faster:
https://github.com/atteneder/UnityJavascriptInteraction However, as soon as
I started adapting it for my game, I started getting exceptions from deep
in the js generated from the C and C# code. FYI
